---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cosmo-eks
  region: eu-central-1
  version: "1.17"

availabilityZones: ["eu-central-1a", "eu-central-1b", "eu-central-1c"]

managedNodeGroups:
- name: nodegroup
  desiredCapacity: 3
  ssh:
    allow: true
    publicKeyName: cosmo-eks

# To enable all of the control plane logs, uncomment below:
# cloudWatch:
#  clusterLogging:
#    enableTypes: ["*"]

secretsEncryption:
  keyARN: arn:aws:kms:eu-central-1:066650776666:key/0d30dc1b-9410-48c2-9a5a-73a975919a10
