---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cosmo-eks
  region: eu-central-1
  version: "1.17"

managedNodeGroups:
- name: nodegroup
  desiredCapacity: 3
  ssh:
    allow: true
    publicKeyName: cosmo-eks
  privateNetworking: true

vpc:
  subnets:
    private:
      eu-central-1a: { id: subnet-f0d5629a }
      eu-central-1b: { id: subnet-8cd537f0 }
      eu-central-1c: { id: subnet-88dc2dc4 }

# To enable all of the control plane logs, uncomment below:
# cloudWatch:
#  clusterLogging:
#    enableTypes: ["*"]

secretsEncryption:
  keyARN: arn:aws:kms:eu-central-1:066650776666:key/0d30dc1b-9410-48c2-9a5a-73a975919a10
